# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7d8224385613b366519d02f0eaa482fd289d47a3beba76f64aeec1720c76186ee4ce81974b1fd740f23bb10fbc161a7a77c05418d879ed577546e78e9439fbd

test:
  secret_key_base: 0c91aef7976595fd82e61750413dbbab68f84158d4dff3d95ce26d0be9da88789c292275d3a4e205c58361987b7fee62c688b25ee5d9990dad890fd3f93dba61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
